export const AUTH_LOGIN_RESPONSE = {
  SUCCESS: 'SUCCESS',
  NOT_CONFIRMED: 'NOT_CONFIRMED',
  PASSWORD_RESET_NEEDED: 'PASSWORD_RESET_NEEDED',
  CREDENTIALS_WRONG: 'CREDENTIALS_WRONG',
  UNKOWN_ERROR: 'UNKOWN_ERROR'
}

export const AUTH_LOGIN_RESPONSE_MESSAGES = {
  [AUTH_LOGIN_RESPONSE.SUCCESS]: {}
}
